import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SesionProvider } from "@/global/sesion";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coffe app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SesionProvider>
          <main className="md:px-8 px-4">{children}</main>
        </SesionProvider>
      </body>
    </html>
  );
}
